terraform-script: Extend script for inventory
status-im/infra-template pull request #11
Opened 2024-09-02 09:32 UTC by markoburcul

Extend terraform.py script to populate inventory file with variables `ansible_become_method`, `ansible_become_user` and `ansible_shell_type`. The values for these variables are fetched from terraform state if present, otherwise the defaults are set.

Referenced issue: https://github.com/status-im/infra-template/issues/10

2024-09-03 08:36 UTC, jakubgs requested changes

2024-09-03 08:36 UTC, jakubgs commented on ansible/terraform.py
> +            'data_center={7} region={8} dns_entry={9}\n'
This approach is kinda static, couldn't we make this dynamic? What's the contents of `host.host_vars`? Is it just stuff that we set in the Terraform module? If so then we could generalize this a bit, something like:
```python
In [9]: " ".join("%s=%s" % (k,v) for k,v in host_vars.items())
Out[9]: 'env=dummy stage=dummy data_center=dummy region=dummy dns_entry=dummy'
```
Why make it static when it could be dynamic and take into account any vars we add in the future?

2024-09-04 08:57 UTC, markoburcul commented on ansible/terraform.py
> +            'data_center={7} region={8} dns_entry={9}\n'
I agree with your statement, better to make it fully dynamic. In the `host.host_vars` we have (as an example):
```bash
(Pdb) host.host_vars
{'ansible_host': '138.68.123.228', 'data_center': 'do-ams3', 'dns_domain': 'status.im', 'dns_entry': 'cache-01.do-ams3.nix.ci.status.im', 'env': 'nix', 'hostname': 'cache-01.do-ams3.nix.ci', 'region': 'ams3', 'stage': 'ci'}
```
So what we could do to make it fully dynamic is to do it like this:
```python
for hostname, host in sorted(inventory.hosts.items()):
   text += f"{hostname} " + " ".join("%s=%s" % (k,v) for k,v in host.host_vars.items()) + "\n"
```

2024-09-04 16:19 UTC, yakimant approved these changes

2024-09-04 16:19 UTC, yakimant commented on ansible/terraform.py
> +        text += f"{hostname} " + " ".join("%s=%s" % (k,v) for k,v in host.host_vars.items()) + "\n"
I would use f-strings instead of `%`.
Maybe also splitting into 2 lines.
```suggestion
vars_text = " ".join(f"{k}={v}" for k,v in host.host_vars.items())
text += f"{hostname} {vars_text}\n"
```

2024-09-04 17:06 UTC, jakubgs commented on ansible/terraform.py
> +            'data_center={7} region={8} dns_entry={9}\n'
Hm, but we probably should drop the `hostname` field right? To not duplicate it.

2024-09-04 17:08 UTC, jakubgs approved these changes
This is better, but we should filter out the duplicate `hostname`.

2024-09-10 09:41 UTC, markoburcul commented on ansible/terraform.py
> +            'data_center={7} region={8} dns_entry={9}\n'
I've removed the `hostname` field.

2024-09-12 11:42 UTC, jakubgs approved these changes
Looks good, I tested it, works well. My only worry is that it might result in some key order re-shuffling at some point, but right now it doesn't, so probably fine.

Apparently since Python 3.6 standard dicts preserve key order anyway:
https://stackoverflow.com/a/40007169

2024-09-12 12:52 UTC, merged