Makefile: add direnv-check to verify it is loaded
status-im/infra-template pull request #18
Opened 2024-10-16 18:09 UTC by jakubgs

Result:

![image](https://github.com/user-attachments/assets/46f8c4b2-2e03-4d10-bf65-7f55bc137634)

Also added a way for users to provide their own method of loading the Vault token.

2024-10-17 08:13 UTC, siddarthkay approved these changes
I tested this locally and it works well

2024-10-17 15:24 UTC, apentori requested changes

2024-10-17 15:24 UTC, apentori commented on .envrc.secrets
> +    export VAULT_HTTP_TOKEN=$(vault_token_provider)
The var should be `VAULT_TOKEN`

2024-10-18 13:03 UTC, yakimant approved these changes
Beautiful!

2024-10-18 13:18 UTC, markoburcul approved these changes
Works like a charm.

2024-10-21 13:38 UTC, apentori approved these changes

2024-10-21 13:49 UTC, merged